### PR TITLE
fixes issues on social layouting so that the card is not cut by margins

### LINKED ISSUE #57: text and likes on card is truncated on screens between 600 and 950
The text on the cards on the blog page is truncated to the right, they seem to be hidden by some other element of the dom

image

### PR DESCRIPTION
**Pull request by cuzuco2**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #57 on Mike's repo

Test URLs:
- Before: https://impala--jzachari.hlx.page/blog/
- After: https://issue-57b--impala--jzachari.hlx.page/blog/

### CODE REVIEW

**Comment by cuzuco2** [comment]
@jzachari Please approve this, I think it does fix well the issues we had

**Comment by cuzuco2** [comment]
@jzachari I think yyou have an issue with your cache, I don't see this issue
image

**Comment by jzachari** [comment]
I still have the issue after using an incognito window.  The issue appears to be also related to the browser px height.  It only seems to happen when my browser window height is less than roughly 1000px.

**Comment by cuzuco2** [comment]
@jzachari Ok I see this, I fixed that too, there was some overlapping within the cards vertically. Can you check again please?

**Comment by jzachari** [comment]
Awesome, looks good!

**Pull request merged**
